baseURL = 'https://stockholm-leather-social.se/'
languageCode = 'en-us'
title = 'Stockholm Leather Social'
theme = "shibui"
defaultContentLanguage = "en"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 2

[params]
  description = "Stockholm Leather Social"

  [params.social]
    instagram = "stockholm.leather.social"

  [params.author]
    name = "Stockholm Leather Social"
    email = "stockholm.leather.social@gmail.com"
