baseURL = 'https://stockholm-leather-social.se/'
languageCode = 'en-us'
title = 'SLS'
theme = "shibui"
defaultContentLanguage = "en"

[menu]
  [[menu.main]]
    name = "HOME"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "DATES"
    url = "/dates/"
    weight = 2
  [[menu.main]]
    name = "ABOUT"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 3
  [[menu.main]]
    name = "REGNBÅGSPRISET"
    url = "/regnbagspriset/"
    weight = 4

[params]
  description = "Stockholm Leather Social"
  showreadingtime = false

  [params.social]
    instagram = "stockholm.leather.social"

  [params.author]
    name = "Stockholm Leather Social"
    email = "stockholm.leather.social@gmail.com"
